### ISSUE TITLE
Are all the annotations in the RSICD dataset used?

### ISSUE THREAD

**Issue by jaycecd** [YonghaoXu/Txt2Img-MHN#4]
Great work and thanks to the authors for their hard work! 

But I have a little doubt:

We know that an image in the RSICD dataset corresponds to 5 annotations, I would like to ask that when predicting or training, for each image, is one annotation randomly selected, or are all 5 annotations used to generate the image? 
If all of them are used, will it result in semantic duplication?

Looking forward to your reply!

**Comment by YonghaoXu** [comment]
Hi, we randomly select one annotation for each image to train the model at different iterations. This is implemented by the `__getitem__` function in the `TextImageDataset` class.

**Comment by jaycecd** [comment]
There is no problem with the training, but if it is still randomly selected in the prediction, it will result in inconsistent IS and FID scores evaluated as a result of each experiment. So, have you tested how much the IS and FID scores differ across multiple experiments?

**Comment by jaycecd** [comment]
In the prediction phase, the first annotation is taken fixed and the problem is solved
