### ISSUE TITLE
VQVAE is significantly slower than VQGAN

### ISSUE THREAD

**Issue by jaycecd** [YonghaoXu/Txt2Img-MHN#5]
Hi, I'm using the pre-trained weights you provided for inference on RSICD, VQGAN is running fine but VQVAE is so slow that it's rendering it almost unusable, I've counted the intervals between before and after image generation and it's taking about 10 minutes to generate an image.

The inference is done on a 4090, is there something else about VQVAE that requires additional configuration?

**Comment by YonghaoXu** [comment]
Hi, this is normal since VQVAE adopts a downsampling rate of 8 while the default downsampling rate in VQGAN is 16. You can also consider using multiple GPUs to accelerate the process.

**Comment by jaycecd** [comment]
I have seen that you have given multi-GPU acceleration instructions for training process, may I ask that inference can also be done like training using `CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7,...` Perform acceleration?

**Comment by YonghaoXu** [comment]
Yes, you can adapt the code with `torch.nn.DataParallel()` similar to the training script to support inference with multiple GPUs.

**Comment by jaycecd** [comment]
Okay, thank you very much for your reply
